# https://taskfile.dev
version: '2'

tasks:
  default:
    silent: true
    cmds:
      - task --list

  os:
    silent: true
    desc: "Configure macOS default system"
    cmds:
      - bash macos/macos.sh
      - echo "Setup OS done!"

  zsh:
    silent: true
    desc: "Install oh my zsh and source zsh extension file"
    cmds:
      - rm -rf $HOME/.oh-my-zsh
      - rm -rf $HOME/.config/base16-shell
      - chsh -s $(which zsh);
      - curl -L http://install.ohmyz.sh | sh
      - rm -rf $HOME/.zshrc
      - ln -s $PWD/zsh/.zshrc $HOME/.zshrc
      - ln -s $PWD/zsh/alex $HOME/.oh-my-zsh/custom/alex
      - mkdir -p $HOME/.config
      - git clone https://github.com/chriskempson/base16-shell.git $HOME/.config/base16-shell
      - curl -L -o ~/.oh-my-zsh/custom/themes/materialshell.zsh-theme https://raw.githubusercontent.com/carloscuesta/materialshell/master/materialshell.zsh
      - git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
      - git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/zsh-completions
      - echo "Reload your terminal and run base16_tomorrow-night command"

  neovim:
    silent: true
    desc: "Install NeoVim"
    cmds:
      - brew install luarocks luv
      - brew install --HEAD luajit
      - brew install --HEAD neovim
      - vim -E +PlugInstall +qall || true
      - echo "Setup NeoVim done!"

  links:
    silent: true
    desc: "Create all dotfiles symlinks"
    cmds:
      - bash links.sh
      - echo "Setup Links done!"

  yabai-install:
    silent: true
    desc: "Installing Yabai for Window Management"
    cmds:
      - brew install koekeishiya/formulae/yabai
      - sudo yabai --install-sa
      - brew services start yabai
      - killall Dock
      - brew install koekeishiya/formulae/skhd
      - brew services start skhd
      - chmod +x ~/.yabairc
      - chmod +x ~/.skhdrc
      - echo "you have to run on Recovery OS csrutil enable --without debug --without fs"

  yabai-remove:
    silent: true
    desc: "Uninstalling Yabai for Window Management"
    cmds:
      - brew services stop yabai skhd
      - sudo yabai --uninstall-sa
      - brew uninstall yabai skhd
      - rm -rf /usr/local/var/log/yabai
      - rm ~/.yabairc
      - rm ~/.skhdrc
      - rm /tmp/yabai_$USER.lock
      - rm /tmp/yabai_$USER.socket
      - rm /tmp/yabai-sa_$USER.socket
      - killall Dock

  yabai-update:
    silent: true
    desc: "Update Yabai for Window Management"
    cmds:
      - brew services stop yabai
      - brew upgrade yabai
      - brew services start yabai
      - sudo yabai --uninstall-sa
      - sudo yabai --install-sa
      - killall Dock

  spaceship:
    silent: true
    desc: "Install Spaceship ZSH Plugins"
    cmds:
      - git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
      - git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

  ctf:
    silent: true
    desc: "CTF Hacking Tools"
    cmds:
      - brew update
      - export HOMEBREW_NO_AUTO_UPDATE=1
      - brew install aircrack-ng bfg binutils binwalk cifer dex2jar dns2tcp fcrackzip foremost hashpump hydra john
      - brew install knock netpbm nmap pngcheck socat sqlmap tcpflow tcpreplay tcptrace ucspi-tcp xpdf xz
      - brew cleanup

  alacritty:
    silent: true
    desc: "Configuration for Alacritty"
    cmds:
      - brew update
      - brew install alacritty
      - mkdir -p $HOME/.config/alacritty
      - ln -s $PWD/config/alacritty.yml $HOME/.config/alacritty/alacritty.yml
