- name: Install MacOS Packages
  hosts: localhost
  become: false
  vars:
    brew_cask_packages:
      - font-fira-code
      - font-hack
      - font-hack-nerd-font
      - font-roboto-mono
      - font-source-code-pro-for-powerline
      - font-cascadia
      - arc
      - transmit
      - vlc
      - raycast
      - dropbox
      - protonvpn
      - sequel-ace
      - setapp
      - slack
      - sublime-text
      - microsoft-office
      - postman
      - 1password
      - visual-studio-code
      - viscosity
      - iterm2
    brew_packages:
      - php
      - node
      - yarn
      - go
      - nvm
      - ack
      - ccat
      - cloc
      - coreutils
      - ctags
      - curl
      - dnsmasq
      - eza
      - ffmpeg
      - fswatch
      - fzf
      - gawk
      - gd
      - git
      - go-task
      - htop
      - httpie
      - inetutils
      - jq
      - jd
      - mas
      - pv
      - pwgen
      - reattach-to-user-namespace
      - rsync
      - sbt
      - screen
      - ripgrep
      - shellcheck
      - ssh-copy-id
      - tree
      - glab
      - watch
      - wget
      - wrk
      - jlhonora/lsusb/lsusb
      - hadolint
      - mycli
      - speedtest
      - luarocks
      - luv
      - ripgrep
      - kotlin-language-server
      - gopls
      - hashicorp/tap/vault
      - joemiller/taps/vault-token-helper
      - saml2aws
      - qwerty-fr
      - colima
      - docker
      - docker-compose
      - openapi-generator
      - switchaudio-osx
      - openssl
    install_homebrew_if_missing: false
    upgrade_homebrew_packages: false

  pre_tasks:
    - name: Ensuring Homebrew Is Installed
      stat:
        path: /usr/local/bin/brew
      register: homebrew_check

    - name: Fail If Homebrew Is Not Installed and install_homebrew_if_missing Is False
      fail:
        msg: Homebrew is missing...Install from http://brew.sh/
      when:
        - not homebrew_check.stat.exists
        - not install_homebrew_if_missing

    - name: Installing Homebrew
      shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      when:
        - not homebrew_check.stat.exists
        - install_homebrew_if_missing

  tasks:
    - name: Updating Homebrew
      homebrew:
        update_homebrew: true
      when: homebrew_check.stat.exists

    - name: Tap a Homebrew repository, state present
      community.general.homebrew_tap:
        name: eddieantonio/eddieantonio, homebrew/bundle, homebrew/cask-fonts, homebrew/cask-versions, homebrew/services, jlhonora/lsusb, sambadevi/powerlevel9k, go-task/tap, teamookla/speedtest, hashicorp/tap, shivammathur/php
        state: present

    - name: Upgrading Homebrew Packages
      homebrew:
        upgrade_all: "{{ upgrade_homebrew_packages }}"
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

    - name: Installing Homebrew Cask Packages
      homebrew_cask:
        name: "{{ brew_cask_packages }}"
        state: present
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

    - name: Installing Homebrew Packages
      homebrew:
        name: "{{ brew_packages }}"
        state: present
      register: result
      until: result is successful
      when: homebrew_check.stat.exists
