#!/bin/zsh
set -e

# launchctl bootstrap "gui/$(id -u)" ~/Library/LaunchAgents/com.alexlombry.backup_secure.plist
# launchctl enable "gui/$(id -u)/com.alexlombry.backup_secure"

# Test-run immediately (optional)
# launchctl kickstart -k "gui/$(id -u)/com.alexlombry.backup_secure"

# tail -n 200 ~/Library/Logs/dailyscript.err
# tail -n 200 ~/Library/Logs/dailyscript.out

BACKUP_ROOT="$HOME/backups"
TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
WORK_DIR="$BACKUP_ROOT/backup_$TIMESTAMP"
ARCHIVE="$BACKUP_ROOT/backups_$TIMESTAMP.tar.gz"
ENCRYPTED_ARCHIVE="$ARCHIVE.gpg"

echo "Create $WORK_DIR folder"
mkdir -p "$WORK_DIR"

echo "Copying files..."

# Mandatory dotfiles
for file in .zshrc .zprofile .zshenv .gitconfig .gitignore_global; do
  [ -e "$HOME/$file" ] && cp -R "$HOME/$file" "$WORK_DIR"
done

# Sensible folders
for dir in .ssh .gnupg .config .docker .aws .kube; do
  [ -d "$HOME/$dir" ] && cp -R "$HOME/$dir" "$WORK_DIR"
done

# Critical library
mkdir -p "$WORK_DIR/Library"
for libdir in "Keychains"; do
  [ -d "$HOME/Library/$libdir" ] && cp -R "$HOME/Library/$libdir" "$WORK_DIR/Library"
done

echo "Creating archive"
tar -czf "$ARCHIVE" -C "$BACKUP_ROOT" "backup_$TIMESTAMP"

echo "GPG Cypher (AES-256)..."
security find-generic-password -w -s "backup-gpg" -a "$USER" \
| gpg --batch --yes --pinentry-mode loopback --passphrase-fd 0 \
      --symmetric --cipher-algo AES256 \
      --output "$ENCRYPTED_ARCHIVE" "$ARCHIVE"

echo "Removing uncyphered files..."
rm -rf "$WORK_DIR"
rm -f "$ARCHIVE"

echo "Cyphered backup created :"
echo "$ENCRYPTED_ARCHIVE"

sshpass -p $(security find-generic-password -w -s "backup-gpg" -a "$USER") \
rsync -av --progress \
  -e "ssh -o StrictHostKeyChecking=no" \
  "$ENCRYPTED_ARCHIVE" \
  "NaetoH@192.168.1.53:/volume1/Documents/"

## To restore the archive :
# gpg --output backup.tar.gz --decrypt backups_DATE.tar.gz.gpg
# tar -xzf backup.tar.gz
#
# 0 9 * * * /bin/zsh -lc '/Users/alex.lombry/dotfiles/install/scripts/backup_secure' >> /Users/alex.lombry/Library/Logs/dailyscript.out 2>> /Users/alex.lombry/Library/Logs/dailyscript.err
