# https://taskfile.dev
version: "3"

tasks:
  default:
    silent: true
    cmds:
      - task --list

  os:
    silent: true
    desc: "Configure macOS default system"
    cmds:
      - bash macos.sh
      - echo "Setup OS done!"

  brew:
    silent: false
    desc: "Install Homebrew bundle"
    cmds:
      - HOMEBREW_NO_AUTO_UPDATE=1 brew bundle --file=BrewFile

  stow:
    silent: true
    desc: "Apply symlinks with GNU Stow"
    cmds:
      - cd $HOME/dotfiles/stow
      - stow --adopt -t "$HOME" zsh git config else
      - echo "Symlinks applied!"

  mise:
    silent: false
    desc: "Install languages and tools with Mise"
    cmds:
      - mise install
      - mise use -g

  neovim:
    silent: true
    desc: "Install NeoVim"
    cmds:
      - brew install luarocks luv
      - brew install --HEAD luajit
      - brew install --HEAD neovim

  chad:
    silent: true
    desc: "Install ChadVIM"
    cmds:
      - git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && nvim

  bundle:
    silent: false
    desc: "Install the current BrewFile bundle"
    cmds:
      - HOMEBREW_NO_AUTO_UPDATE=1 brew bundle

  setup:
    desc: "Complete setup for a new MacBook"
    cmds:
      - task: stow
      - task: os
      - task: brew
      - task: mise
      - task: neovim
      - echo "🚀 MacBook Setup Complete! Please restart your terminal."
