version: '3.7'

services:
  mysql:
    container_name: mysql_perso_57
    image: mysql:5.7
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: alex
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    restart: on-failure
